In [18]:
import numpy as np

In [21]:
A = np.array([
    [1, 0,-1],
    [1, 2, 1],
    [2, 2, 3]
])

Identity_Matrix = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])

eigenvalues, eigenvectors = np.linalg.eig(A)

D = np.diag(eigenvalues)

P = eigenvectors

P_inv = np.linalg.inv(P)

A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nIdentity Matrix")
print(Identity_Matrix)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors")
print(P)

print("\nDiagonal matrix D:")
print(D)

print("\nMatrix of P")
print(P)

print("\nInverse of matrix P:")
print(P_inv)

print("\nInverse of matrix A:")
print(A_inv)

Matrix A:
[[ 1  0 -1]
 [ 1  2  1]
 [ 2  2  3]]

Identity Matrix
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Eigenvalues:
[2. 3. 1.]

Eigenvectors
[[-6.66666667e-01 -4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01  4.08248290e-01 -7.07106781e-01]
 [ 6.66666667e-01  8.16496581e-01  5.19864223e-16]]

Diagonal matrix D:
[[2. 0. 0.]
 [0. 3. 0.]
 [0. 0. 1.]]

Matrix of P
[[-6.66666667e-01 -4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01  4.08248290e-01 -7.07106781e-01]
 [ 6.66666667e-01  8.16496581e-01  5.19864223e-16]]

Inverse of matrix P:
[[-3.00000000e+00 -3.00000000e+00 -3.22542807e-15]
 [ 2.44948974e+00  2.44948974e+00  1.22474487e+00]
 [-0.00000000e+00 -1.41421356e+00  7.07106781e-01]]

Inverse of matrix A:
[[ 0.66666667 -0.33333333  0.33333333]
 [-0.16666667  0.83333333 -0.33333333]
 [-0.33333333 -0.33333333  0.33333333]]
